project:
  type: website
  output-dir: docs

website:
  title: "Alex Goebel"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/agoebel-vt/agoebel-vt.github.io
      - icon: linkedin
        href: https://www.linkedin.com/in/alex-goebel-2655b5114/
format:
  html:
    theme: cosmo
    css: styles.css



